### ISSUE TITLE
not able to build using 1.5.1 for io.js

### ISSUE THREAD

**Issue by christkv** [rvagg/nan#257]
I'm not sure why it's not build correctly. I suspect some change in nan.h makes the NanNew method signature wrong.

https://github.com/christkv/kerberos/blob/master/lib/kerberos_context.cc#L33

```
node-gyp@1.0.2  /usr/local/lib/node_modules/node-gyp
node@0.10.32
christkv:kerberos ck$ node-gyp configure
gyp info it worked if it ends with ok
gyp info using node-gyp@1.0.2
gyp info using node@0.10.32 | darwin | x64
gyp info spawn python
gyp info spawn args [ '/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/ck/coding/projects/kerberos/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/ck/.node-gyp/0.10.32/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/ck/.node-gyp/0.10.32',
gyp info spawn args   '-Dmodule_root_dir=/Users/ck/coding/projects/kerberos',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info ok
christkv:kerberos ck$ node-gyp build
gyp info it worked if it ends with ok
gyp info using node-gyp@1.0.2
gyp info using node@0.10.32 | darwin | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/kerberos/lib/kerberos_context.o
../lib/kerberos_context.cc:33:31: error: no matching function for call to 'NanNew'
  Local<FunctionTemplate> t = NanNew<FunctionTemplate>(KerberosContext::New, v8::Handle<v8::Value>(), v8::Handle<v8::Signa...
                              ^~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan_new.h:195:1: note: candidate template ignored: couldn't infer template argument 'A0'
NanNew(A0 arg0, A1 arg1, A2 arg2) {
^
../node_modules/nan/nan_new.h:177:1: note: candidate function template not viable: requires 0 arguments, but 3 were provided
NanNew() {
^
../node_modules/nan/nan_new.h:183:1: note: candidate function template not viable: requires single argument 'arg0', but 3
      arguments were provided
NanNew(A0 arg0) {
^
../node_modules/nan/nan_new.h:189:1: note: candidate function template not viable: requires 2 arguments, but 3 were provided
NanNew(A0 arg0, A1 arg1) {
^
../node_modules/nan/nan.h:146:14: note: candidate function template not viable: requires 1 argument, but 3 were provided
v8::Local<T> NanNew(v8::Handle<T>);
             ^
../node_modules/nan/nan_new.h:201:1: note: candidate function template not viable: requires 4 arguments, but 3 were provided
NanNew(A0 arg0, A1 arg1, A2 arg2, A3 arg3) {
^
../node_modules/nan/nan_new.h:208:43: note: candidate function template not viable: requires single argument 'p', but 3 arguments
      were provided
template <typename T> inline v8::Local<T> NanNew(v8::Persistent<T> const& p);
                                          ^
1 error generated.
make: *** [Release/obj.target/kerberos/lib/kerberos_context.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Darwin 13.3.0
gyp ERR! command "node" "/usr/local/bin/node-gyp" "build"
gyp ERR! cwd /Users/ck/coding/projects/kerberos
gyp ERR! node -v v0.10.32
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
```

**Comment by kkoopa** [comment]
This has been fixed, will be released in the next patch. 5ef813bf06c93725d03d17a91ee48d2c66dd7b3b

As a workaround, you can either rename one of the offending New method overloads, move one of them into a separate scope, or do a typecast `NanNew<v8::FunctionTemplate>(static_cast<NAN_METHOD((*))>(New));`
