### ISSUE TITLE
NanThrowError is not throwing in iojs 1.5.1, node 0.12 or node 0.11

### ISSUE THREAD

**Issue by stephenmathieson** [rvagg/nan#294]
I'm hoping I'm doing something wrong, but [this](https://gist.github.com/stephenmathieson/6593406b5d791db4345b) example works fine under node 0.10, but not 0.11, 0.12 or iojs 1.5.1.

## iojs 1.5.1:

```
$ make test
node_modules/.bin/node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@1.0.3
gyp info using node@1.5.1 | darwin | x64
gyp info spawn python
gyp info spawn args [ '/Users/stephenmathieson/repos/github.com/stephenmathieson/wut/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/stephenmathieson/repos/github.com/stephenmathieson/wut/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/stephenmathieson/repos/github.com/stephenmathieson/wut/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/stephenmathieson/.node-gyp/1.5.1/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/stephenmathieson/.node-gyp/1.5.1',
gyp info spawn args   '-Dmodule_root_dir=/Users/stephenmathieson/repos/github.com/stephenmathieson/wut',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/wut/binding.o
  SOLINK_MODULE(target) Release/wut.node
  SOLINK_MODULE(target) Release/wut.node: Finished
gyp info ok 
node test
has 'foo'
'foo' is not a string
we didnt throw or return???
'foo' is a string
```

## node 0.12.0:

```
$ make test
node_modules/.bin/node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@1.0.3
gyp info using node@0.12.0 | darwin | x64
gyp info spawn python
gyp info spawn args [ '/Users/stephenmathieson/repos/github.com/stephenmathieson/wut/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/stephenmathieson/repos/github.com/stephenmathieson/wut/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/stephenmathieson/repos/github.com/stephenmathieson/wut/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/stephenmathieson/.node-gyp/0.12.0/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/stephenmathieson/.node-gyp/0.12.0',
gyp info spawn args   '-Dmodule_root_dir=/Users/stephenmathieson/repos/github.com/stephenmathieson/wut',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/wut/binding.o
  SOLINK_MODULE(target) Release/wut.node
  SOLINK_MODULE(target) Release/wut.node: Finished
gyp info ok 
node test
has 'foo'
'foo' is not a string
we didnt throw or return???
'foo' is a string
```

## node 0.11.16:

```
$ make test
node_modules/.bin/node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@1.0.3
gyp info using node@0.11.16 | darwin | x64
gyp info spawn python
gyp info spawn args [ '/Users/stephenmathieson/repos/github.com/stephenmathieson/wut/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/stephenmathieson/repos/github.com/stephenmathieson/wut/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/stephenmathieson/repos/github.com/stephenmathieson/wut/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/stephenmathieson/.node-gyp/0.11.16/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/stephenmathieson/.node-gyp/0.11.16',
gyp info spawn args   '-Dmodule_root_dir=/Users/stephenmathieson/repos/github.com/stephenmathieson/wut',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/wut/binding.o
  SOLINK_MODULE(target) Release/wut.node
  SOLINK_MODULE(target) Release/wut.node: Finished
gyp info ok 
node test
has 'foo'
'foo' is not a string
we didnt throw or return???
'foo' is a string
```

## node 0.10.36:

```
$ make test
node_modules/.bin/node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@1.0.3
gyp info using node@0.10.36 | darwin | x64
gyp info spawn python
gyp info spawn args [ '/Users/stephenmathieson/repos/github.com/stephenmathieson/wut/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/stephenmathieson/repos/github.com/stephenmathieson/wut/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/stephenmathieson/repos/github.com/stephenmathieson/wut/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/stephenmathieson/.node-gyp/0.10.36/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/stephenmathieson/.node-gyp/0.10.36',
gyp info spawn args   '-Dmodule_root_dir=/Users/stephenmathieson/repos/github.com/stephenmathieson/wut',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/wut/binding.o
  SOLINK_MODULE(target) Release/wut.node
  SOLINK_MODULE(target) Release/wut.node: Finished
gyp info ok 
node test
has 'foo'
'foo' is not a string
we didnt throw or return???
'foo' is a string

Error: foo must be a string
    at Object.<anonymous> (/Users/stephenmathieson/repos/github.com/stephenmathieson/wut/test.js:2:28)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3
make: *** [test] Error 8
```

**Comment by bnoordhuis** [comment]
From your sample code:

```c++
        NanThrowError("foo must be a string");
```

That should be:

```c++
        return NanThrowError("foo must be a string");
```

**Comment by stephenmathieson** [comment]
@bnoordhuis you're right, thanks.
